# Exported from Render on 2025-07-14T11:53:59Z
services:
  - type: web
    name: qudemo-python-api
    env: python
    plan: free
    buildCommand: |
      cd backend/pythonn
      pip install -r requirements-python312.txt
      playwright install chromium
    startCommand: |
      cd backend/pythonn
      python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 5001
      - key: RENDER
        value: true
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 0
      maxInstances: 1
    resources:
      cpu: 0.5
      memory: 512MB
    disk:
      name: data
      mountPath: /opt/render/project/src/backend/pythonn/uploads
      sizeGB: 1